production: &production
  system: &system
    path: # CLI application, can be null
    domain: # CLI application, can be null
    protocol: # CLI application, can be null
    # display exceptions
    debug: no
    # profilers
    profilers: &profilers
      enabled: no
      queries:
        limit: 20 # display last x queries
      # automatically append profilers
      append:
        cli: yes # append to every cli response
      helpers: # used by append above
        - queries
        - console
        - benchmark
    
    # modules
    modules:
      system:
        path: vendor/ovos/php-module-system/application
        controllers: true
        views: true
    
    # tests
    tests:
      - vendor/ovos/php-library/tests
    
    # services (optionally loaded global objects)
    services:
      container: Services
      cli:
        - Events # handles errors and exceptions
        - Benchmark # measures request speed
        - Cache # cache
  
  # cli
  cli:
    executable: php
  
  # connections
  connections: &connections
    mysql:
      type: mysql
      host: !ENV MYSQL[HOST]
      database: !ENV MYSQL[DATABASE]
      username: !ENV MYSQL[USERNAME]
      password: !ENV MYSQL[PASSWORD]
    redis:
      type: redis
      host: !ENV REDIS[HOST]
      port: !ENV REDIS[PORT]
      database: !ENV REDIS[DATABASE]
      connect_timeout: 1
      read_timeout: 1
      slow_log:
        enabled: yes
        threshold: 2.0
  
  # mysql
  database: &database
    connection: mysql
    encryption:
      method: AES-256-CBC
      key: zA%$6&z9J,s_[;66[7r
  
  # cache
  cache: &cache
    enabled: yes
    prefix: !ENV CACHE[PREFIX]
    perishable: &cache-perishable
      compression:
        enabled: yes
        threshold: 2048
      # cache queueing
      queue:
        enabled: yes
        lock_ttl_s: 1
        wait_timeout_s: 2
        backoff_min_ms: 5
        backoff_max_ms: 25
    persistent: &cache-persistent
      connection: redis
      store: Redis # Redis or Redisearch
      store_options:
        clean_tags: no
      compression:
        enabled: yes
        threshold: 2048
      # cache queueing
      queue:
        enabled: yes
        lock_ttl_ms: 2000
        wait_attempts: 3

development: &development
  <<: *production
  system: &development-system
    <<: *system
    debug: yes
    # profilers
    profilers:
      <<: *profilers
      enabled: yes    